#!/bin/bash

# Get the C file name from the environment variable
c_file=$CFILE

# Generate the output file name
output_file="${c_file%.*}.s"

# Generate the assembly code using GCC
gcc -S -masm=intel "$c_file" -o "$output_file"
